### ISSUE TITLE
ImportError: cannot import name 'ChaliceIntegration' from 'sentry_chalice'

### ISSUE THREAD

**Issue by bolinocroustibat** [cuenca-mx/sentry-chalice#1]
Hi! Thanks for this module.
I installed it using `pip install sentry_chalice` (or with Poetry using `poetry add sentry_chalice`).
But then I got `ImportError: cannot import name 'ChaliceIntegration' from 'sentry_chalice'` when importing it. Did I miss something, or is it too early to use the module?

**Comment by matin** [comment]
@bolinocroustibat can you upgrade your version (`pip install -U sentry-chalice`)? We just released `0.1.0` to PyPi

**Comment by bolinocroustibat** [comment]
Thank you, it works now.
